"""Phase 22c.3-08 — relax idempotency_keys.run_id FK + NOT NULL for chat path.

The Plan 19-05 baseline declared ``idempotency_keys.run_id`` as
``Text NOT NULL FK -> runs.id``. Phase 22c.3-08 extends the
``IdempotencyMiddleware`` to also cover ``POST /v1/agents/:id/messages``
(D-39); that path's success body carries ``message_id`` (an
``inapp_messages.id`` UUID) — NOT a ``runs.id``. Writing the cache row
with ``message_id`` would trip the FK + NOT NULL constraint.

This migration relaxes the column to "any opaque cache identifier":

  1. DROP the FK constraint to ``runs.id``.
  2. ALTER the column to NULLABLE (defense in depth — no caller will
     send NULL today, but the cache logic should not require a non-null
     external id; the cached body itself carries the canonical id).

Both changes are SAFE on existing data — every existing row has a
non-NULL ``run_id`` value AND those values still reference real
``runs`` rows; we are just removing the DB-side enforcement so the
chat path can write a ``message_id`` instead.

Downgrade: re-add the NOT NULL + FK. Operationally, downgrade requires
that no chat-path rows exist (their ``run_id`` value isn't a valid
``runs.id``); production rollback would need a manual purge step. This
migration is reversible at the DDL level only — left intentionally
explicit so a downgrade in test environments works for round-trip
verification.

Revision ID: 008_idempotency_relax_run_fk
Revises: 007_inapp_messages
Create Date: 2026-04-30
"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "008_idempotency_relax_run_fk"
down_revision = "007_inapp_messages"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The FK constraint name was auto-generated by Alembic in 001 — there
    # is no explicit name in the baseline migration. Postgres assigns
    # ``idempotency_keys_run_id_fkey`` by default for an inline FK on a
    # single column. Use the conventional name.
    op.drop_constraint(
        "idempotency_keys_run_id_fkey",
        "idempotency_keys",
        type_="foreignkey",
    )
    op.alter_column(
        "idempotency_keys",
        "run_id",
        nullable=True,
    )


def downgrade() -> None:
    # Tighten back: NOT NULL + FK -> runs.id. Will fail on a DB that has
    # any chat-path cache row (run_id holds a message_id that is not in
    # runs). Test-only round-trip: clean rows first.
    op.alter_column(
        "idempotency_keys",
        "run_id",
        nullable=False,
    )
    op.create_foreign_key(
        "idempotency_keys_run_id_fkey",
        "idempotency_keys",
        "runs",
        ["run_id"],
        ["id"],
    )
