import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { ParticleBackground } from "@/components/particle-background"

export default function TermsPage() {
  return (
    <main className="relative min-h-screen overflow-x-hidden bg-background">
      <ParticleBackground />
      <Navbar />
      
      <div className="relative z-10 mx-auto max-w-3xl px-4 pb-16 pt-24 sm:px-6 sm:pb-20 sm:pt-32 lg:px-8">
        <h1 className="mb-8 text-3xl font-bold text-foreground sm:text-4xl">Terms of Service</h1>
        <p className="mb-6 text-sm text-muted-foreground">Last updated: April 14, 2026</p>

        <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground">
          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p className="text-sm leading-relaxed">
              By accessing or using Agent Playground (&quot;Service&quot;), you agree to be bound by these 
              Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">2. Description of Service</h2>
            <p className="text-sm leading-relaxed">
              Agent Playground provides a platform for creating, deploying, and managing AI agents. 
              Our Service includes web-based tools, APIs, and integrations with third-party services.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">3. User Accounts</h2>
            <p className="text-sm leading-relaxed">
              You must create an account to use certain features of the Service. You are responsible 
              for maintaining the confidentiality of your account credentials and for all activities 
              that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">4. Acceptable Use</h2>
            <p className="mb-3 text-sm leading-relaxed">You agree not to use the Service to:</p>
            <ul className="list-inside list-disc space-y-1 text-sm">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Transmit malicious code or engage in hacking</li>
              <li>Harass, abuse, or harm others</li>
              <li>Generate illegal, harmful, or deceptive content</li>
              <li>Circumvent usage limits or access controls</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">5. AI Usage Guidelines</h2>
            <p className="text-sm leading-relaxed">
              You are responsible for the outputs generated by your AI agents. You must ensure your 
              agents comply with applicable laws, do not generate harmful content, and include 
              appropriate disclosures when interacting with end users.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">6. Intellectual Property</h2>
            <p className="text-sm leading-relaxed">
              You retain ownership of content you create using our Service. By using the Service, 
              you grant us a license to host and display your content as necessary to provide the 
              Service. Agent Playground and its original content remain the property of Agent 
              Playground, Inc.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">7. Payment Terms</h2>
            <p className="text-sm leading-relaxed">
              Paid plans are billed in advance on a monthly or annual basis. Fees are non-refundable 
              except as required by law. We reserve the right to modify pricing with 30 days notice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">8. Termination</h2>
            <p className="text-sm leading-relaxed">
              We may suspend or terminate your access to the Service at any time for violations of 
              these Terms or for any other reason at our discretion. You may cancel your account at 
              any time through your account settings.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">9. Disclaimer of Warranties</h2>
            <p className="text-sm leading-relaxed">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE 
              THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">10. Limitation of Liability</h2>
            <p className="text-sm leading-relaxed">
              IN NO EVENT SHALL AGENT PLAYGROUND BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, 
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">11. Changes to Terms</h2>
            <p className="text-sm leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify you of material 
              changes via email or through the Service. Continued use after changes constitutes 
              acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-foreground">12. Contact</h2>
            <p className="text-sm leading-relaxed">
              If you have questions about these Terms, please contact us at{" "}
              <a href="mailto:legal@agentplayground.dev" className="text-primary hover:underline">
                legal@agentplayground.dev
              </a>
            </p>
          </section>
        </div>
      </div>
      
      <Footer />
    </main>
  )
}
