#!/usr/bin/env bash
# Phase 19 Hetzner deployment — idempotent pull/migrate/roll script.
#
# Flow:
#   1. Optional git pull (skip with NO_PULL=1)
#   2. Ensure deploy/secrets/pg_password exists (auto-generate if missing)
#   3. Compute DOCKER_GID from host /var/run/docker.sock
#   4. Pull base images (postgres + caddy)
#   5. Build api_server image with correct DOCKER_GID
#   6. Start postgres, wait for healthy
#   7. Ensure agent_playground_api database exists (init-api-db.sh)
#   8. [BLOCKING] alembic upgrade head — schema must apply BEFORE traffic
#   9. Roll api_server + caddy
#  10. Probe http://localhost:8000/healthz from the box
set -euo pipefail

cd "$(dirname "$0")"
COMPOSE="docker compose -f docker-compose.prod.yml"

echo "[deploy] starting"

if [[ "${NO_PULL:-}" != "1" ]]; then
  echo "[deploy] git pull"
  (cd .. && git pull --ff-only) || { echo "[deploy] git pull failed"; exit 1; }
fi

echo "[deploy] ensuring secrets/pg_password exists"
if [[ ! -s secrets/pg_password ]]; then
  mkdir -p secrets
  head -c 32 /dev/urandom | base64 | tr -d '\n' > secrets/pg_password
  chmod 600 secrets/pg_password
  echo "[deploy] generated secrets/pg_password (32 random bytes, base64)"
fi

# Compute host Docker socket GID so container user can access it (Pitfall 5).
DOCKER_GID="$(stat -c %g /var/run/docker.sock 2>/dev/null || echo 999)"
export DOCKER_GID

# Write .env.prod so docker-compose can interpolate ${POSTGRES_PASSWORD}
# into DATABASE_URL for the api_server service. The password itself stays
# in secrets/pg_password; .env.prod is regenerated each deploy.
PG_PASSWORD="$(cat secrets/pg_password)"
{
  echo "# Auto-generated by deploy/deploy.sh — DO NOT EDIT."
  echo "POSTGRES_PASSWORD=${PG_PASSWORD}"
} > .env.prod
chmod 600 .env.prod

echo "[deploy] pulling base images"
$COMPOSE pull postgres caddy

echo "[deploy] building api_server with DOCKER_GID=$DOCKER_GID"
$COMPOSE build --build-arg "DOCKER_GID=$DOCKER_GID" api_server

echo "[deploy] starting postgres"
$COMPOSE up -d postgres

echo "[deploy] waiting for postgres healthy"
for _ in $(seq 1 30); do
  if $COMPOSE exec -T postgres pg_isready -U ap >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "[deploy] running init-api-db.sh"
bash ./init-api-db.sh

# [BLOCKING] apply schema before api_server takes traffic.
echo "[deploy] running alembic upgrade head"
$COMPOSE run --rm api_server alembic upgrade head

echo "[deploy] rolling api_server + caddy"
$COMPOSE up -d api_server caddy

echo "[deploy] waiting for /healthz"
for _ in $(seq 1 20); do
  if curl -fsS http://localhost:8000/healthz >/dev/null 2>&1; then
    echo "[deploy] ok — api_server /healthz responding"
    exit 0
  fi
  sleep 1
done

echo "[deploy] FAILED: /healthz not responding after 20s"
$COMPOSE logs --tail 100 api_server
exit 1
